### ISSUE TITLE
Diagramas de componetes 

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo_tec#1]
Link en la wiki

https://github.com/SistemasTecTlaxiaco/CoffeTec/wiki/6.-Diagrama-de-componentes
REPORTE DE LA PRÁCTICA 10
[Rep10.pdf](https://github.com/user-attachments/files/18041015/Rep10.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
De acuerdo a la rúbrica obtuviste 28%.

**Comment by Daniel-Velasco-Lopez** [comment]
La elaboración de su documento cumple con las espectativas de la rúbrica, por lo que han alcanzo un 28%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
